apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ingress-nginx.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --watch-ingress-without-class=true
