apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: kimjy1116/cloud3:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          value: "qf+-jk+h4d+9@2r!%=frdh!ng7ek@l!54%^sqskttk(rvd%&so"
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "cloud"
        - name: POSTGRES_PASSWORD
          value: "dkagh"
        - name: POSTGRES_HOST
          value: "postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
