apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: kimjy1116/cloud18:t4
        imagePullPolicy: Always  
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          value: "xq@l%m@+$-&lg)*+&-rchwne+!fj@)t*(8u5h3#h=um%lun2iw"
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "cloud"
        - name: POSTGRES_PASSWORD
          value: "dkagh"
        - name: POSTGRES_HOST
          value: "postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SUPERUSER_USERNAME
          value: "admin"
        - name: DJANGO_SUPERUSER_EMAIL
          value: "admin@example.com"
        - name: DJANGO_SUPERUSER_PASSWORD
          value: "admin"
