
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- base

patchesStrategicMerge:
- add-labels-patch.yaml

components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter  

