apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- game
- nfs
- blog
- ingress      
- gke
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: not-important
      namespace: app
    spec:
      template:
        metadata:
          labels:
            app: microservice
        spec:
          volumes:
          - name: nfs-volume
            persistentVolumeClaim:
              claimName: nfs-pvc
          containers:
          - name: not-important
            volumeMounts:
            - name: nfs-volume
              mountPath: /mnt/nfs
  target:
    kind: Deployment
    namespace: app

secretGenerator:
- name: mysql-pass
  literals:
  - password=$MysqlDbPW

components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
- components/ingress-nginx
