apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- game
- nfs
patches:
- patch: |-
    [
      {
        "op": "add",
        "path": "/spec/template/metadata/labels/app",
        "value": "microservice"
      },
      {
        "op": "add",
        "path": "/spec/template/spec/volumes/-",
        "value": {
          "name": "nfs-volume",
          "persistentVolumeClaim": {
            "claimName": "nfs-pvc"
          }
        }
      },
      {
        "op": "add",
        "path": "/spec/template/spec/containers/0/volumeMounts/-",
        "value": {
          "name": "nfs-volume",
          "mountPath": "/mnt/nfs"
        }
      }
    ]
  target:
    kind: Deployment
    namespace: app
components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
