apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
patches:
- path: add-labels-patch.yaml
  target:
    kind: Deployment
    namespace: app
components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
