apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
patches:
- patch: |-
    [
      {
        "op": "add",
        "path": "/spec/template/metadata/labels/app",
        "value": "microservice"
      }
    ]
  target:
    kind: Deployment
    namespace: app
- path: add-nfs-volume-patch.yaml
  target:
    kind: Deployment
    name: not-important
- path: add-nfs-volume-patch.yaml
  target:
    kind: StatefulSet
    name: not-important      
components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
- components/nfs-provisioner
