apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- main
- game 
  #- nfs
- blog

secretGenerator:
- name: mysql-pass
  literals:
  - password=$MysqlDbPW

components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
  #- components/ingress-nginx
  #- components/ingress
