apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- game
- patches/nfs/nfs-pv.yaml
- patches/nfs/nfs-pvc.yaml
- patches/network-policies/allow-nfs-network-policy.yaml  # 이 줄을 추가
patches:
- patch: |-
    [
      {
        "op": "add",
        "path": "/spec/template/metadata/labels/app",
        "value": "microservice"
      }
    ]
  target:
    kind: Deployment
    namespace: app
- path: patches/nfs/nfs-patch.yaml
  target:
    kind: Deployment
components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
