
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- base

components:
- compononts/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter  

