apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- game
  #- patches/nfs/nfs-resources.yaml
patches:
- patch: |-
    [
      {
        "op": "add",
        "path": "/spec/template/metadata/labels/app",
        "value": "microservice"
      }
    ]
  target:
    kind: Deployment
    namespace: app
      #transformers:
      #- transformers/add-nfs-volume.yaml
components:
- components/cadvisor
- components/rbac
- components/prometheus
- components/grafana
- components/node-exporter
- components/alertmanager
