apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: kimjy1116/cloud18:t2
        command: ["python"]
        args: ["manage.py", "migrate"]
        env:
        - name: DJANGO_SECRET_KEY
          value: "xq@l%m@+$-&lg)*+&-rchwne+!fj@)t*(8u5h3#h=um%lun2iw"
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "cloud"
        - name: POSTGRES_PASSWORD
          value: "dkagh"
        - name: POSTGRES_HOST
          value: "postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SUPERUSER_USERNAME
          value: "admin"
        - name: DJANGO_SUPERUSER_EMAIL
          value: "admin@example.com"
        - name: DJANGO_SUPERUSER_PASSWORD
          value: "admin"
      restartPolicy: Never
