apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 52.78.1.170
    path: "/nfs4-share3"
