apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-nfs-volume
patch: |-
  - op: add
    path: /spec/template/spec/volumes
    value: []
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts
    value: []
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: nfs-volume
      mountPath: /shared-data
target:
  kind: Deployment
