apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-backendconfig
  namespace: app
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: game-backendconfig
  namespace: game
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
