apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "gke-proj"
    networking.gke.io/managed-certificates: "managed-cert"
spec:
  rules:
  - host: cloud.providehighvalue.com
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend-external.app.svc.cluster.local
            port:
              number: 80
      - path: /wordpress
        pathType: Prefix
        backend:
          service:
            name: wordpress.app.svc.cluster.local
            port:
              number: 80
      - path: /2048
        pathType: Prefix
        backend:
          service:
            name: deployment-2048.game.svc.cluster.local
            port:
              number: 10000
      - path: /mario
        pathType: Prefix
        backend:
          service:
            name: mario.game.svc.cluster.local
            port:
              number: 77
