apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: cloud.providehighvalue.com
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend-external
            port:
              number: 80
      - path: /wordpress
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: game
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: cloud.providehighvalue.com
    http:
      paths:
      - path: /2048
        pathType: Prefix
        backend:
          service:
            name: deployment-2048
            port:
              number: 10000
      - path: /mario
        pathType: Prefix
        backend:
          service:
            name: mario
            port:
              number: 77
