apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: main
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP  # 또는 NodePort, 환경에 따라 선택
