apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: main
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: kimjy1116/cloud:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: DJANGO_SECRET_KEY  # 환경 변수로 시크릿 키 설정
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: SECRET_KEY
        - name: ALLOWED_HOSTS  # 환경 변수로 ALLOWED_HOSTS 설정
          value: "your-domain.com"
        - name: POSTGRES_DB  # 환경 변수로 데이터베이스 이름 설정
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER  # 환경 변수로 데이터베이스 사용자 설정
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD  # 환경 변수로 데이터베이스 비밀번호 설정
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST  # 데이터베이스 호스트 설정
          value: "postgresql"
        - name: POSTGRES_PORT  # 데이터베이스 포트 설정
          value: "5432"
