apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: yoyoyellow/django:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "cloud"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_PORT
          value: "5432"
        volumeMounts:
        - name: django-data
          mountPath: /app/data  # 애플리케이션에서 데이터를 저장할 경로
      volumes:
      - name: django-data
        persistentVolumeClaim:
          claimName: django-nfs-pv  # 이 부분만 변경됨
