apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-nfs-pvc
  namespace: main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: django-nfs-pv
