apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  namespace: main
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
