apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-nfs-pvc
  namespace: main
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: django-nfs-pv  # 위에서 정의한 PV 이름을 명시적으로 지정
