apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx-rolebinding
  namespace: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ingress-nginx
roleRef:
  kind: Role
  name: ingress-nginx-role
  apiGroup: rbac.authorization.k8s.io
