apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring  # ConfigMap이 위치할 네임스페이스
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring  # 'node-exporter'가 있는 네임스페이스
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter

