apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog
type: Opaque
data:
  password: cm9vdHBhc3N3b3Jk  # 'rootpassword'의 base64 인코딩
  wordpress-password: d29yZHByZXNzcGFzc3dvcmQ=  # 'wordpresspassword'의 base64 인코딩
