apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: nfs
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 52.78.1.170
    path: "/var/nfs/sql"
