apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: nfs
    app: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 52.78.1.170
    path: "/var/nfs/post"
