apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: blog
data:
  wp-config.php: |
    <?php
    define('DB_NAME', 'wordpress');
    define('DB_USER', 'wordpress');
    define('DB_PASSWORD', '${WORDPRESS_DB_PASSWORD}');
    define('DB_HOST', 'wordpress-mysql');
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
    
    // WordPress 데이터베이스 테이블 접두사
    $table_prefix = 'wp_';
    
    // 디버깅 모드
    define('WP_DEBUG', false);
    
    // 나머지 설정은 WordPress가 자동으로 처리하도록 합니다.
    if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');
    
    require_once(ABSPATH . 'wp-settings.php');
    ?>
