apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: blog
data:
  wp-config.php: |
    <?php
    define('DB_NAME', 'wordpress');
    define('DB_USER', 'wordpress');
    define('DB_PASSWORD', '${WORDPRESS_DB_PASSWORD}');
    define('DB_HOST', 'wordpress-mysql');
    // 기타 필요한 WordPress 설정
    ?>
