apiVersion: kustomize.config.k8s.io/v1alpha1  # 여기를 v1beta1에서 v1alpha1로 변경
kind: Component

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 45.7.1
  releaseName: prometheus
  namespace: monitoring
  includeCRDs: true
  valuesInline:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    alertmanager:
      enabled: true
