apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.12.0
- service-monitors.yaml
- remove-duplicates.yaml
patches:
- path: prometheus-patch.yaml
  target:
    kind: Prometheus
    name: k8s

namespace: monitoring

# 중복 리소스 제거
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: prometheus-k8s
  patch: |
    - op: remove
      path: /metadata/annotations
