apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- prometheus-crds.yaml
- service-monitors.yaml

patches:
- path: prometheus-patch.yaml
  target:
    kind: Prometheus
    name: k8s

# kube-prometheus 참조는 제거
