apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
