apiVersion: apps/v1
kind: Deployment
metadata:
  name: "*"  # 모든 Deployment에 적용
spec:
  template:
    spec:
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: "*"  # 모든 컨테이너에 적용
        volumeMounts:
        - name: nfs-volume
          mountPath: /shared-data
