apiVersion: apps/v1
kind: Deployment
metadata:
  name: "*"
spec:
  template:
    spec:
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - $patch: merge
        volumeMounts:
        - name: nfs-volume
          mountPath: /shared-data
