apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        ports:
        - containerPort: 9090  # 변경된 포트
        volumeMounts:
        - name: cadvisor-mount-rootfs
          mountPath: /container
          mountPropagation: Bidirectional
        - name: cadvisor-mount-cgroup
          mountPath: /sys/fs/cgroup
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "500m"
      volumes:
      - name: cadvisor-mount-rootfs
        hostPath:
          path: /rootfs
      - name: cadvisor-mount-cgroup
        hostPath:
          path: /sys/fs/cgroup
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  ports:
  - port: 9090  # 변경된 포트
    targetPort: 9090  # 변경된 포트
    protocol: TCP
  selector:
    app: cadvisor

