apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  #name: letsencrypt-prod
  name: letsencrypt-staging
spec:
  acme:
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dldzmwn@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
