#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: django-ingress
#  namespace: main
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: cloud.providehighvalue.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
    #  tls:
    #  - hosts:
    #    - shop.providehighvalue.com
    #    - blog.providehighvalue.com
  rules:
  - host: shop.providehighvalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: blog.providehighvalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
    #  tls:
    #  - hosts:
    #    - 2048.providehighvalue.com
    #    - mario.providehighvalue.com
  rules:
  - host: 2048.providehighvalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deployment-2048
            port:
              number: 10000
  - host: mario.providehighvalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mario
            port:
              number: 77          
