apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: app
spec:
  domains:
    - cloud.providehighvalue.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: game
spec:
  domains:
    - cloud.providehighvalue.com
