apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: game
spec:
  selector:
    app: minecraft
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP

