apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: game
  labels:
    app: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
--- 
apiVersion: v1
kind: Service
metadata:
   name: mario
   namespace: game
spec:
  selector:
    app: mario
  ports:
  - name: http
    port: 77
    protocol: TCP
    targetPort: 7897
  type: ClusterIP
