apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi  # 필요에 따라 조정
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 43.203.223.91  # EC2 인스턴스의 퍼블릭 IP
    path: "/var/nfs/general"  # 확인된 NFS 공유 경로
