apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi  # 필요에 따라 조정
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 52.78.1.170 # EC2 인스턴스의 퍼블릭 IP
    path: "/var/nfs/general"  # 확인된 NFS 공유 경로

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mysql
spec:
  storageClassName: ""  # 이 줄을 추가
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 52.78.1.170
    path: "/var/nfs/mysql/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-wordpress
spec:
  storageClassName: ""  # 이 줄을 추가
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 52.78.1.170
    path: "/var/nfs/wordpress"
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: django-pv
#spec:
#  capacity:
#    storage: 5Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: nfs
#  nfs:
#    server: 52.78.1.170
#    path: "/var/nfs/django"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 52.78.1.170
    path: "/var/nfs/postgresql"
