apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi  # 필요에 따라 조정
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 52.78.1.170 # EC2 인스턴스의 퍼블릭 IP
    path: "/var/nfs/general"  # 확인된 NFS 공유 경로
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce          # ReadWriteOnce RWO (1:1 마운트, 읽기 쓰기)
  nfs:
    server: 52.78.1.170 # NFS-Server 의 IP
    path: /nfs4-share       # NFS 저장소
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 52.78.1.170 # NFS-Server 의 IP
    path: /nfs4-share2      # NFS 저장소
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
  namespace: main
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server:  52.78.1.170
    path: /nfs4-share3
