apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: main
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: kimjy1116/cloud:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: SECRET_KEY
        - name: ALLOWED_HOSTS
          value: "your-domain.com"
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_DB
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: combined-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_HOST
          value: "postgresql"
        - name: DATABASE_PORT
          value: "5432"
