apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: game
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
